SerpentCODGameAgentPlugin:
  frame_handler: PLAY
SerpentCODGamePlugin:
  fps: 100
SerpentFPSGameAgentPlugin:
  frame_handler: PLAY
SerpentTestingGamePlugin:
  fps: 2
SerpenttwoGameAgentPlugin:
  frame_handler: PLAY
